### ISSUE TITLE
Datapack missing required tags prevents loading worlds with any datapack

### ISSUE THREAD

**Issue by NielsPilgaard** [Team-Arcanum/Nordic-Arcanum-Issues#1]
Hi there!

Your internal datapack is faulty, it's preventing both clients and servers to loading worlds. The log isn't very helpful, but I'm guessing you accidentally used `minecraft:` instead of `forge:` in a recipe.

[Log exert](https://gist.github.com/NillerMedDild/266b3138453b3b00b20f534ca439a94c)
[Full client latest.log](https://gist.github.com/NillerMedDild/a0f51c9387eda04fba40dd45fcb0c375)

### Versions
`nordicarcanum-1.16.3-0.5.0`
`arcanumapi-1.16.3-0.3.0`
Forge-1.16.3-34.1.25

**Comment by LordSkittles** [comment]
I am unable to reproduce this issue. Checking all instances of the tags within my internal datapack shows no times do I use "minecraft:" for any of my ores or any part of those crystals. Could you please detail what mods you have installed?

**Comment by LordSkittles** [comment]
You have also not provided the full log, that full log does not contain that exert you have provided so I am unable to see what is happening around it

**Comment by NielsPilgaard** [comment]
I did provide the full log, there's a little banner that says `This file has been truncated, but you can view the full file.` 
Here's the link anyway: https://gist.githubusercontent.com/NillerMedDild/a0f51c9387eda04fba40dd45fcb0c375/raw/ab6efa5314dab80836eae5fe8d54a9beef14cbe0/gistfile1.txt

I didn't supply that one because it has no styling and is harder to read up-front.

**Comment by LordSkittles** [comment]
Ah you are correct, sorry, I was view this on my phone

**Comment by NielsPilgaard** [comment]
No worries, I'll try to find the mod conflict and provide a list if I can't :)

**Comment by LordSkittles** [comment]
Thanks so much! I wanna sort this issue for you lol. Honestly love playing with Enigmatica so would be awesome to see my mod in there :P

**Comment by NielsPilgaard** [comment]
No luck so far :/ I was unable to join a world and trigger a debug crash, so here's the contents of the mods folder instead:

https://gist.github.com/NillerMedDild/8a5b0566f76f2a5cd13b3beed300bec7

None of those mods use amethyst, garnet or carnelian so I'm not sure what's up.

**Comment by LordSkittles** [comment]
I'll look further into it later, I'm currently at work, but I will get this sorted as soon as possible!

**Comment by LordSkittles** [comment]
Would you mind humoring me and just running it on your machine with only my mod? I just want to confirm it's definitely my mod and not a conflict

**Comment by NielsPilgaard** [comment]
Works just fine with only Nordic Arcanum & Arcanum API, will try to add more mods, hopefully it breaks early on :P

Ruled out so far:
- KubeJS
- JAOPCA
- Productive Bees

Removed all custom configs and scripts from E6 in-dev, same issue. So it's... some mod ><

**Comment by LordSkittles** [comment]
Cheers mate. Well at least it's good to know it's not me! Haha. When we work out which mod it is, I'll look into how to fix it.

**Comment by LordSkittles** [comment]
Is there any mod that adds recipe changes that you've got? Could that potentially have scripts that could potentially be trying to change the tag of my crystals?

**Comment by LordSkittles** [comment]
I'm having a go at finding the mod conflict for you now

**Comment by LordSkittles** [comment]
Have you tried without Interactio? I'm wondering if that might be the problem?

**Comment by NielsPilgaard** [comment]
Nope, can't reproduce the issue with Interactio + Arcanum :(

**Comment by LordSkittles** [comment]
The weird thing is that it's crashing the game. Missing tags like this shouldn't crash with recipes.

**Comment by NielsPilgaard** [comment]
I've seen it before with Productive Bees, using tags that never get created in-code.

**Comment by LordSkittles** [comment]
The weird thing is I never directly use tags within my code. Only within a
recipe and even then, I've checked all of my recipes for that and it
definitely isn't there, so there definitely is some sort of conflict. I'll
keep investigating for you

**Comment by LordSkittles** [comment]
I'll also triple check my recipes just in case, but I doubt it's my mod since it's not reproducible with it outside the pack

**Comment by NielsPilgaard** [comment]
Thank you, I'm also trying to find the culprit. I also really doubt it's your mod :)

**Comment by LordSkittles** [comment]
No worries mate, like I said! Really wanna see my mod in a pack!

**Comment by NielsPilgaard** [comment]
I think I found it! EmbellishCraft and/or it's lib MapperBase

**Comment by LordSkittles** [comment]
Awesome! I'll look into seeing what's going on with it!

**Comment by LordSkittles** [comment]
Can you try updating those two mods to the latest versions? I can boot the game with those mods installed and nordic arcanum

**Comment by LordSkittles** [comment]
But I had the latest versions

**Comment by LordSkittles** [comment]
Weirdly, I can boot the game with those mods on those versions actually!

**Comment by NielsPilgaard** [comment]
The issue isn't booting, it's starting worlds :)

**Comment by LordSkittles** [comment]
Ah yes, but regardless, I could do that too

**Comment by LordSkittles** [comment]
Could you attempt updating those mods?

**Comment by NielsPilgaard** [comment]
Not in Enigmatica, but I'll give it a shot in a test instance :)

**Comment by LordSkittles** [comment]
Cool, let me know how you go

**Comment by NielsPilgaard** [comment]
I had the same findings, closing for the time being :D thanks for the help!

**Comment by LordSkittles** [comment]
No worries! I'm glad I could assist! So it was the version of those mods then? Not me?

**Comment by NielsPilgaard** [comment]
Yeah it definitely seems like it :) hard to tell for sure without your source code tbh.

**Comment by LordSkittles** [comment]
Anything I can do further to assist you?

**Comment by NielsPilgaard** [comment]
No thanks, but I'll make sure to open an issue if I find anything :P
